import pandas as pd
import networkx as nx
import csv
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
names = []
values = []
numbers = []
with open ("GS.csv", "r") as f:
    reader = csv.reader(f, delimiter = ",")
    
    for i in reader:
     names.append(i[0])
     values.append(int(i[1]))
     #numbers.append(int(i[2]))

#print(values)
#print(numbers)

plt.xticks((range(len(names))),names)
plt.tight_layout()
plt.bar(names,values, log = True)

plt.xlabel('Studies Containing Only One Single Disease-Gene Association Grouped by Curated Data Sources')
plt.ylabel('Number of Single Disease-Gene Associations Generated By Studies')
plt.title('Gold Standard Associations Grouped by Data Sources')
plt.xticks(rotation=90)
plt.show()

